version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messagingapp_api
    depends_on:
      - db
    ports:
      - "port1:port2"
    networks:
      - nginx-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: messagingapp_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "db_port:db_port"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true

volumes:
  sql_data: